# Conclusion
The study found that most countries have seen significant improvements in the coverage of improved water sources and sanitation facilities from 1990 to 2023, with many non-LDCs approaching 100% coverage of improved water sources. However, the pace of basic service improvements in the least developed countries has been slower, particularly in landlocked countries and Southeast Asia, which still face severe infrastructure deficits. The prevalence of clean fuels has increased globally, but Asia's high level of clean fuel prevalence is significantly lower than that of Africa, indicating regional imbalances in development. Limitations: During the research process, for regions with limited data and few statistical years, it was not possible to accurately capture the changes in basic service coverage. Future Research Directions: For incomplete data, adopt more effective methods to supplement the data, connect with datasets of other relevant factors, and further explore the causes of trend changes.Lessons Learned: When exploring the correlation between two variables and encountering outliers, additional variables can be introduced for grouping to identify the causes of the anomalies. 